# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_widgets.ui'
#
# Created: Fri Oct 29 11:13:03 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(481, 404)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.line_outputShader = QtWidgets.QLineEdit(self.groupBox)
        self.line_outputShader.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_outputShader.setFont(font)
        self.line_outputShader.setObjectName("line_outputShader")
        self.gridLayout.addWidget(self.line_outputShader, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.line_outputData = QtWidgets.QLineEdit(self.groupBox)
        self.line_outputData.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_outputData.setFont(font)
        self.line_outputData.setObjectName("line_outputData")
        self.gridLayout.addWidget(self.line_outputData, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.btn_setExportShaderPath = QtWidgets.QPushButton(self.groupBox)
        self.btn_setExportShaderPath.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_setExportShaderPath.setFont(font)
        self.btn_setExportShaderPath.setObjectName("btn_setExportShaderPath")
        self.gridLayout.addWidget(self.btn_setExportShaderPath, 0, 2, 1, 1)
        self.btn_setExportDataPath = QtWidgets.QPushButton(self.groupBox)
        self.btn_setExportDataPath.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_setExportDataPath.setFont(font)
        self.btn_setExportDataPath.setObjectName("btn_setExportDataPath")
        self.gridLayout.addWidget(self.btn_setExportDataPath, 2, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_exportAll = QtWidgets.QPushButton(self.groupBox)
        self.btn_exportAll.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_exportAll.setFont(font)
        self.btn_exportAll.setObjectName("btn_exportAll")
        self.horizontalLayout.addWidget(self.btn_exportAll)
        self.btn_exportSelection = QtWidgets.QPushButton(self.groupBox)
        self.btn_exportSelection.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_exportSelection.setFont(font)
        self.btn_exportSelection.setObjectName("btn_exportSelection")
        self.horizontalLayout.addWidget(self.btn_exportSelection)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(0, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_inputShader = QtWidgets.QLineEdit(self.groupBox_2)
        self.line_inputShader.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_inputShader.setFont(font)
        self.line_inputShader.setObjectName("line_inputShader")
        self.gridLayout_2.addWidget(self.line_inputShader, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.btn_setImportDataPath = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_setImportDataPath.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_setImportDataPath.setFont(font)
        self.btn_setImportDataPath.setObjectName("btn_setImportDataPath")
        self.gridLayout_2.addWidget(self.btn_setImportDataPath, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.line_inputData = QtWidgets.QLineEdit(self.groupBox_2)
        self.line_inputData.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_inputData.setFont(font)
        self.line_inputData.setObjectName("line_inputData")
        self.gridLayout_2.addWidget(self.line_inputData, 2, 1, 1, 1)
        self.btn_setImportShaderPath = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_setImportShaderPath.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_setImportShaderPath.setFont(font)
        self.btn_setImportShaderPath.setObjectName("btn_setImportShaderPath")
        self.gridLayout_2.addWidget(self.btn_setImportShaderPath, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.line_lineGeoNamespace = QtWidgets.QLineEdit(self.groupBox_2)
        self.line_lineGeoNamespace.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_lineGeoNamespace.setFont(font)
        self.line_lineGeoNamespace.setObjectName("line_lineGeoNamespace")
        self.gridLayout_2.addWidget(self.line_lineGeoNamespace, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_import = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_import.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_import.setFont(font)
        self.btn_import.setObjectName("btn_import")
        self.horizontalLayout_2.addWidget(self.btn_import)
        self.btn_importToSelection = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_importToSelection.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_importToSelection.setFont(font)
        self.btn_importToSelection.setObjectName("btn_importToSelection")
        self.horizontalLayout_2.addWidget(self.btn_importToSelection)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(0, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Shader IO", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", " Export ", None, -1))
        self.line_outputShader.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "ma", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Data Path:", None, -1))
        self.line_outputData.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "json", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Shader Path:", None, -1))
        self.btn_setExportShaderPath.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_setExportDataPath.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.btn_exportAll.setText(QtWidgets.QApplication.translate("MainWindow", "Export All", None, -1))
        self.btn_exportSelection.setText(QtWidgets.QApplication.translate("MainWindow", "Export Selection", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", " Import ", None, -1))
        self.line_inputShader.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "ma", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Data Path:", None, -1))
        self.btn_setImportDataPath.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Shader Path:", None, -1))
        self.line_inputData.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "json", None, -1))
        self.btn_setImportShaderPath.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Geometry NS:", None, -1))
        self.line_lineGeoNamespace.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "namespace", None, -1))
        self.btn_import.setText(QtWidgets.QApplication.translate("MainWindow", "Import", None, -1))
        self.btn_importToSelection.setText(QtWidgets.QApplication.translate("MainWindow", "Import to Selection", None, -1))

